# Generated by Django 3.0.7 on 2020-06-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boilerplatecode',
            table='BoilerPlateCode',
        ),
    ]
