# Generated by Django 3.0.7 on 2020-06-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200614_0347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoilerPlateCode',
        ),
    ]
